spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/recipe_dev
    username: recipe_dev
    password: zse44rfv
    platform: mariadb
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    # properties:
    #   javax:
    #     persistence:
    #       schema-generation:
    #         create-source: metadata
    #         scripts:
    #           action: create
    #           create-target: create_schema.sql
